version: '3'
services:
  app_1:
    build:
      context: .
      dockerfile: ./app.dockerfile
    container_name: app_1
    volumes:
      - ./src/app_1:/var/www/html
      - vol1:/var/www/html/storage
    ports:
      - "8080:80"
    networks:
      - network-1
      - network-2
    environment:
      - URL_PATH=app_2
  app_2:
    build:
      context: .
      dockerfile: ./app.dockerfile
    container_name: app_2
    volumes:
      - ./src/app_2:/var/www/html
      - vol2:/var/www/html/storage
    ports:
      - "8081:80"
    networks:
      - network-2
      - network-3
    environment:
      - URL_PATH=app_3
  app_3:
    build:
      context: .
      dockerfile: ./app.dockerfile
    container_name: app_3
    volumes:
      - ./src/app_3:/var/www/html
      - vol3:/var/www/html/storage
    ports:
      - "8082:80"
    networks:
      - network-3
    environment:
      - URL_PATH=app_sync
  app_sync:
    build:
      context: .
      dockerfile: ./app.dockerfile
    container_name: app_sync
    volumes:
      - ./src/sync:/var/www/html
      - vol1:/var/www/html/storage/app_1
      - vol2:/var/www/html/storage/app_2
      - vol3:/var/www/html/storage/app_3
    ports:
      - "8083:80"
    networks:
      - network-3
networks:
  network-1:
  network-2:
  network-3:
volumes:
  vol1:
    name: training-vol1
  vol2:
    name: training-vol2
  vol3:
    name: training-vol3